name = "speech-club-vote-prototype"
main = "src/index.ts"
compatibility_date = "2026-06-01"

[triggers]
crons = ["0 3 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "speech_club_votes"
database_id = "d98a29cc-2288-41cf-93d6-b5121aa932df"
migrations_dir = "migrations"
